apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider openshift
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    io.kompose.service: db
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: opensubmit
        - name: POSTGRES_PASSWORD
          value: opensubmit
        - name: POSTGRES_USER
          value: opensubmit
        image: ' '
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-volume
      restartPolicy: Always
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - db
      from:
        kind: ImageStreamTag
        name: db:9
    type: ImageChange
status: {}
