apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider openshift
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: exec
  name: exec
spec:
  replicas: 1
  selector:
    io.kompose.service: exec
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: exec
    spec:
      containers:
      - env:
        - name: OPENSUBMIT_SERVER_HOST
          value: http://web
        image: ' '
        name: exec
        resources: {}
        tty: true
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - exec
      from:
        kind: ImageStreamTag
        name: exec:latest
    type: ImageChange
status: {}
