apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider openshift
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    io.kompose.service: web
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: OPENSUBMIT_DATABASE_ENGINE
          value: postgresql
        - name: OPENSUBMIT_DATABASE_HOST
          value: db
        - name: OPENSUBMIT_DATABASE_NAME
          value: opensubmit
        - name: OPENSUBMIT_DATABASE_PASSWORD
          value: opensubmit
        - name: OPENSUBMIT_DATABASE_USER
          value: opensubmit
        - name: OPENSUBMIT_DEBUG
          value: "0"
        - name: OPENSUBMIT_LOGIN_DEMO
          value: "1"
        - name: OPENSUBMIT_SERVER_HOSTALIASES
          value: web
        - name: OPENSUBMIT_SERVER_MEDIAROOT
          value: /data/media/
        - name: OPENSUBMIT_SERVER_URL
          value: http://localhost:8000
        image: ' '
        name: web
        ports:
        - containerPort: 80
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /data
          name: data-volume
      restartPolicy: Always
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - web
      from:
        kind: ImageStreamTag
        name: web:latest
    type: ImageChange
status: {}
